newrelic/newrelic-agent-init-container

dotnet/Dockerfile
java/Dockerfile
nodejs/.dockerignore
nodejs/Dockerfile
nodejs/package.json
nodejs/src/newrelicinstrumentation.ts
nodejs/tsconfig.json
php/Dockerfile
python/Dockerfile

Add init containers from https://github.com/newrelic-experimental/newrelic-agent-operator/tree/main/autoinstrumentation and simplify them by adding additional ARGs where needed.
Note Node has not been simplified yet in this regard to reference the version of the node agent from the ARG.

Move init containers from prototype

---

.gitignore
dotnet/Dockerfile

* Updates `Dockerfile` for .NET to use the correct URL for downloading the .NET agent (the previous URL only worked for downloading the latest version).
* Pins `alpine` and `busybox` base images to a specific SHA
* Adds a `.gitignore` file to exclude some files and folders specific to Visual Studio and VS Code.

chore: Update Dockerfile for .NET

---

.github/workflows/dotnet.yml
src/dotnet/Dockerfile
tests/dotnet/Dockerfile
tests/dotnet/chart/.helmignore
tests/dotnet/chart/Chart.yaml
tests/dotnet/chart/templates/deployment.yaml
tests/dotnet/chart/templates/instrumentation.yaml
tests/dotnet/chart/values.yaml
tests/dotnet/test-specs.yml

* Adds a workflow for the .NET init container test and build
* Adds tests for .NET
Things to note:
* ~I'm using [step-security/harden-runner](https://github.com/step-security/harden-runner) on all jobs which is a best practice for identifying and mitigating any potential monkey business by bad actors~ -- Apparently there's some interaction between `harden-runner` and `setup-minikube`. We'll need to look into that at some point.
* The workflow also uses `dorny/paths-filter` to check whether any files relevant to the .NET init container were modified and does not run the `test` job if no files were modified
* I added a `workflow_dispatch` trigger so the workflow (the `test` job, at least) can be manually invoked for testing and debugging.
Much to my surprise and amazement, the `test` job …

ci: Add dotnet ci workflow and tests

---

.github/workflows/check-modified-files.yml
.github/workflows/dotnet.yml
.github/workflows/python.yml

Converts the `check-modified-files` job into a reusable workflow and refactors `dotnet.yml` to call that workflow. Also modifies `python.yml` to use the new workflow.

ci: Refactor dotnet workflow to extract reusable workflow for checking modified files

---

.github/workflows/java.yml
.gitignore
src/java/Dockerfile
src/java/java-agent-download.sh
tests/java/Dockerfile
tests/java/chart/.helmignore
tests/java/chart/Chart.yaml
tests/java/chart/templates/deployment.yaml
tests/java/chart/templates/instrumentation.yaml
tests/java/chart/values.yaml
tests/java/test-specs.yml

Resolves https://github.com/newrelic/newrelic-java-agent/issues/1860
Resolves https://github.com/newrelic/newrelic-java-agent/issues/1861

Add Java e2e tests

---

.github/workflows/dotnet.yml

* run test job on publish
* use `github.ref_name` instead of `github.ref` when looking for the `dotnet` tag suffix

ci: More .NET workflow fixes

---

.github/workflows/dotnet.yml

Updates the dotnet workflow to use `DOTNET_DOCKERHUB_USERNAME` and `DOTNET_DOCKERHUB_TOKEN` secrets to log into Docker Hub.

ci: Use .NET username and token for Docker Hub login

---

.github/workflows/ruby.yml
tests/ruby/Dockerfile
tests/ruby/Gemfile
tests/ruby/Gemfile.lock
tests/ruby/app.rb
tests/ruby/chart/.helmignore
tests/ruby/chart/Chart.yaml
tests/ruby/chart/templates/deployment.yaml
tests/ruby/chart/templates/instrumentation.yaml
tests/ruby/chart/values.yaml
tests/ruby/config.ru
tests/ruby/start.sh
tests/ruby/test-specs.yml

Dockerized Ruby app, k8s setup, CI testing

Add e2e tests for Ruby

---

.github/workflows/test.yml

During a debugging session on the shared test workflow, we found that the license key secret wasn't available to workflow runs when the workflow is in a PR from a fork. To check for the availability of the key, we inserted this job that logs the length of the secret. This check isn't necessary now that we've determined that secrets are available as documented.

chore: Removed diagnostic check for availability of license key

---

.github/workflows/check-modified-files.yml
.github/workflows/dotnet.yml
.github/workflows/test.yml

* Integrates with the ` test.yml` reusable workflow, had to make a couple minor changes. 
* Modified file header to use an `SPDX-License-Identifier` tag as suggested in a thread in #agent-dev, makes things much more compact
* Adds inputs for `workflow_dispatch` to optionally allow publishing an arbitrary version of the agent without requiring a release tag
* Only sets the `latest` tag when publishing from a `release` trigger or when request during manual run
* Updates workflow triggers to match other agent workflows, specifying `paths` to consider before triggering. This might make the `check-modified-files` workflow unnecessary.

ci: .NET workflow tweaks

---

src/dotnet/Dockerfile
src/dotnet/agentinfo.json

The .NET agent already uses `agentinfo.json` to identify the install type for the agent; this PR updates the .NET init container build process to inject an `agentinfo.json` file that identifies the installation as `k8s-operator`.

feat(dotnet): Adds an `agentinfo.json` file and updates Dockerfile to copy that file into the init container.

---

tests/dotnet/Dockerfile
tests/dotnet/newrelic.config
tests/dotnet/test-specs.yml

Adds a `newrelic.config` to the e2e test app that configures a few options to help ensure the .NET agent starts up synchronously. This is aimed at improving e2e test reliability.

test(dotnet): Add `newrelic.config` for test app

---

.github/dependabot.yml
.github/scorecard.yml
.github/workflows/dotnet.yml
.github/workflows/java.yml
.github/workflows/nodejs.yml
.github/workflows/python.yml
.github/workflows/ruby.yml

A few changes aimed at security hardening for this repo:
* Adds top-level default permissions to the language agent workflows. Individual jobs can still specify the permissions they need.
* Adds a `dependabot.yml` to enable Dependabot to open PRs for dependency updates. Note that I've included `docker` in the list of ecosystems; we will need to let it run once or twice to determine whether it is useful or not. 
* Adds a `scorecard.yml` workflow to enable [OpenSSF Scorecard analysis](https://github.com/ossf/scorecard?tab=readme-ov-file#overview-1) of the repo. Issues will appear under the "Security" tab on the repo and can be addressed either with a code change or manual dismissal if the issue isn't relevant.

ci: Security Hardening

---

.github/workflows/repolinter.yml

Updates `repolinter.yml`:
* Pin action versions via SHA tags
* Don't run if triggered by Dependabot (because it isn't necessary)
* Add `Harden Runner` and move permissions to the job level

ci: Cleanup repolinter.yml

---

.github/workflows/publish.yml
.github/workflows/test.yml
src/dotnet/Dockerfile
src/java/Dockerfile
src/nodejs/Dockerfile
src/php/Dockerfile
src/python/Dockerfile
src/ruby/Dockerfile

Updates to address a number of currently open [code scanning alerts](https://github.com/newrelic/newrelic-agent-init-container-releases/security/code-scanning). 
Primarily, updates `Dockerfile` everywhere to pin the source image versions to a `sha256` digest. Note that the digest values were extracted using the [Crane tool](https://github.com/google/go-containerregistry/blob/main/cmd/crane/README.md) (`crane digest <image>`) and will be valid for multi-platform builds.

chore: Code scanning alert fixes

---

.github/workflows/nodejs.yml
.github/workflows/publish.yml

* Fixes an issue where NodeJS's initcontainer name was `newrelic/newrelic-nodejs-init` instead of `newrelic/newrelic-node-init`.

Fix Node Image Name

---

tests/dotnet/chart/templates/deployment.yaml
tests/dotnet/chart/values.yaml

Updates the helm chart for .NET testing to allow the (optional) passing of a value for the `NEW_RELIC_HOST` environment variable.  
The .NET team needs this to accommodate local testing, using our own staging license key. The value defaults to `collector.newrelic.com` so will continue to work correctly in the e2e tests. 
(Note that the .NET team can't use the existing `Makefile`, as it's not Windows-friendly. No big deal though; I've documented the manual steps we need to run.)

Modify the .NET helm chart to allow passing a value for NEW_RELIC_HOST

---

.github/workflows/nodejs.yml

With 11.22.0+ we support Node.js 22. This PR updates the workflow to include this runtime version.  
Closes [NR-286240](https://new-relic.atlassian.net/browse/NR-286240)
[NR-286240]: https://new-relic.atlassian.net/browse/NR-286240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: Added Node 22 to the Node.js workflow

---

README.md

I had to fix this, it's my peeve and technically incorrect.  `/s/NodeJS/Node.js`

docs: fixed Node.js branding

---

.github/workflows/test.yml

Since Dependabot can't have access to secrets, there's no need to try to run the e2e tests (they will always fail).

ci: Skip the e2e tests step for Dependabot PRs.

---

.github/workflows/test.yml
src/python/download_wheels.py

* Fix an issue where init container builds would not properly mark as failed due to an incorrect exit status in minikube.
* See https://github.com/kubernetes/minikube/issues/16576
* An example of proper failing behavior after this fix: https://github.com/newrelic/newrelic-agent-init-container/actions/runs/9999193077/job/27639712100?pr=74
* Fix an issue in downloading the exact agent version being the wrong type after unifying extraction logic with the lambda layers build process.

Fix Python Failures

---

.github/CODEOWNERS

* Rename `@newrelic/dotnet-code-reviewers` to `@newrelic/dotnet` to fix team ownership.

Fix .NET Code Ownership

---

tests/Makefile

* Update Makefile scripting with some improvements.
* Separate operator namespace from test app namespace to prevent issues where the wait condition was waiting forever on the wrong item.
* Change `minikube image build` to `docker build` to avoid issues where image builds fail silently and don't stop the script from continuing.

Makefile Scripting Upgrades

---

.github/workflows/nodejs.yml

This PR removes publishing versions of Node.js agent on 16. We are about to release an agent that no longer supports it and this will avoid creating a broken Node.js 16 Images.
Closes NR-285151

chore: Removed support for Node.js 16

---

.github/dependabot.yml

Weekly scans seem to be a bit too noisy, so let's try monthly for a while.

chore: Change Dependabot scans to Monthly

---

tests/ruby/Gemfile

On November 2, 2024, Ruby library `rackup` released a new version going from v2.1 to v2.2 and despite the minor version bump decided to drop a library dependency on (Ruby web server) `webrick`. We now explicitly declare the `webrick` dependency in our own `Gemfile` manifest.

Fix for Ruby tests

---

.github/workflows/test.yml

Skips the Docker container registry login when a workflow is triggered by Dependabot.

ci: Skip Docker Hub login for Dependot PRs

---

.github/workflows/all_e2e_tests.yml
.github/workflows/dotnet.yml
.github/workflows/java.yml
.github/workflows/nodejs.yml
.github/workflows/php.yml
.github/workflows/python.yml
.github/workflows/ruby.yml

Adds a new workflow that can (only) be triggered manually, which will run E2E tests for all languages. 
Intended to be used in conjunction with Dependabot PRs -- someone will need to kick off this workflow on the Dependabot PR branch and verify that it runs successfully before approving and merging the Dependabot PR.

ci: Add a workflow to manually run e2e tests for all languages

---

src/dotnet/Dockerfile
src/java/Dockerfile
src/nodejs/Dockerfile
src/php/Dockerfile
src/python/Dockerfile
src/ruby/Dockerfile

In an effort to reduce the frequency of Dependabot PRs (and based on a good idea from @nrcventura), this PR updates all `busybox` references to use the `stable` tag instead of `latest`.  The digest was updated to reference the [multi-platform busybox image for the `stable` tag](https://hub.docker.com/layers/library/busybox/stable/images/sha256-afa67e3cea50ce204060a6c0113bd63cb289cc0f555d5a80a3bb7c0f62b95add).

Updates all busybox references to use `stable` instead of `latest`

---

.github/workflows/test.yml
README.md
tests/Makefile

- Installing cert manager no a longer relevant step. Removed from Makefile in #117 
- Key changed from tag -> version - [source](https://github.com/newrelic/k8s-agents-operator/blob/main/charts/k8s-agents-operator/README.md?plain=1#L283)

Update test instructions

---

.github/workflows/test.yml
tests/Makefile
tests/dotnet/chart/templates/instrumentation.yaml
tests/dotnet/test-specs.yml
tests/java/chart/templates/instrumentation.yaml
tests/java/test-specs.yml
tests/nodejs/chart/templates/instrumentation.yaml
tests/nodejs/test-specs.yml
tests/php/chart/templates/instrumentation.yaml
tests/php/test-specs.yml
tests/python/chart/templates/instrumentation.yaml
tests/python/test-specs.yml
tests/ruby/chart/templates/instrumentation.yaml
tests/ruby/test-specs.yml

* Updates all languages to use `v1beta1` API Version for the new operator changes.
* Updates chart value setters to use `controllerManager.manager.image.version` instead of `controllerManager.manager.image.tag`
* Add check to ensure test pods have initcontainer injected before running E2E tests.
* Refactor Makefile scripting to be more clean.

Update to New Operator API Version

---

.github/workflows/php.yml

The PHP Agent has released support for 8.4 on Jan 13

feat(php): add 8.4 support

---

tests/Makefile

The following changes are made to the local testing Makefile. Nothing in CI or production is affected.
* Add the ability to pin the operator container and chart version to test specific versions.
* Combine the local operator build/deploy target with the existing operator target to prevent drift, and make usage more intuitive.

Local Testing Makefile Allow Pinned Operator Version

---

.github/workflows/nodejs.yml

* NodeJS 24 dropped support for `linux/arm` in Docker, and only supports the 64-bit version `linux/arm64`.
* Remove this as an architecture we build for NodeJS 24, but retain it for NodeJS 20 and 22.
* Update default NodeJS image tag to 24 from 22 to match README.
* Add tests for all architectures to prevent regressions.

Fix Issues with NodeJS-24 Builds

---

.github/workflows/python.yml
tests/python/test-specs.yml

* Add specific tests for all supported docker architectures for the Python agent.
* Preventing issues like this [failed NodeJS release](https://github.com/newrelic/newrelic-agent-init-container/actions/runs/16531257674) that didn't catch the removal of 32-bit ARM linux support from the base docker image.

Add Arch Specific Tests for Python

---

tests/nodejs/test-specs.yml

* Tests on `NodeJS 24 - Arm64` are failing consistently due to timeouts. Allow application an additional 10 seconds after starting to ensure emulated Arm runs can start up in time.

Add Longer sleep for NodeJS Tests

---

.github/CODEOWNERS
.github/workflows/dotnet.yml
.github/workflows/publish-windows.yml
.github/workflows/publish.yml
.github/workflows/test-dotnet-windows.yml
src/dotnet-windows/Dockerfile
src/dotnet-windows/agentinfo.json
src/dotnet-windows/dotnet-agent-download.cmd

- Adds init containers for the .NET Agent running on Windows 2022 and Windows 2025.
- Windows requires that the OS match container (for the most part), we need two images.
- Uses existing dotnet.yml workflow,
- Uses a manual docker build and push since the buildx installer does not support windows.
- Doesn't use the existing tests since those require minikube which does not support Windows containers.
- New tests just for .NET on Windows have been added that validate the images build, run, and contain the correct files (not an exhaustive check.)

feat: Add Windows init containers for .NET.

---

.github/workflows/python.yml
src/python/requirements-vendor.txt

* Drop support for Python 3.7 in line with new agent version `v11.0.0`.

Drop Python Version 3.7
